---
title: "assignment"
author: "Nora Beinbrech"
date: "2026-02-27"
output: html_document
---

```{r}
suppressPackageStartupMessages({
  library(AnnotationHub) # to fetch genomes, annotations, etc.
  library(ensembldb)     # to manipulate ensembl gene annotations -> makes local SQL database -> makes it efficient
  library(GenomicRanges) # data structure for genomic ranges 
  library(epiwraps)      # visualization, a package developed for the course
})
library(ggplot2)

```
		
		
```{r download_annotation_data}
# downlaoding what data is available
ah <- AnnotationHub()
# finding & downloading Mus Musculus EnsDb version 102
#query_results <- query(ah, c("Mus Musculus", "EnsDb", "102"))
#print(query_results)
ensdb_mus_musculus <- ah[["AH89211"]]

# finding and downloading mouse genome sequence
#query_results <- query(ah, c("Mus Musculus", "dna_sm", "GRCm38", "2020-10-27"))
#query_results$rdatadateadded
#print(query_results)
dna_seq_mouse <- ah[["AH88477"]]

# finding and downloading drosophila sequence
#query_results <- query(ah, c("Drosophila Melanogaster", "dna_sm", "BDGP6"))
#print(query_results)
#query_results$rdatadateadded
#rev(query_results$ah_id)[1]
dna_seq_drosophila <- ah[["AH49674"]]

```
```{r}
mouse_genes <- genes(ensdb_mus_musculus)

# checking number of protein coding genes 
proteincg_mouse <- mouse_genes[mouse_genes$gene_biotype== "protein_coding"]
n_diff_gene_id <- length(unique(proteincg_mouse$gene_id)) # nuber of different gene IDs
print(n_diff_gene_id)
n_diff_gene_symbols <- length(unique(proteincg_mouse$gene_name)) # nuber of different gene symbols
print(n_diff_gene_symbols)

# load exons sorted by transcripts; and transcripts
exons <- exonsBy(ensdb_mus_musculus, by= "tx")

# load transcripts & filter for protein coding
transcripts_mouse <- transcripts(ensdb_mus_musculus)
pc_transcripts <- transcripts_mouse[transcripts_mouse$tx_biotype== "protein_coding"]

# filter exons for only protein coding transcripts
exons_pc <- exons[pc_transcripts$tx_id]

# get length of exons and sum by transcripts
length_exons <- width(exons_pc)
sum <- sum(length_exons)

#convert to dataframe
sum_df <- data.frame(
     tx_id = names(sum),
    spliced_length = as.numeric(sum))

# plot length of exons as histogram
ggplot(data=sum_df, aes(x=spliced_length))+
  geom_histogram(binwidth = 250)

```





		
		
		

